# from selenium import webdriver
# from selenium.webdriver.common.by import By

# driver = webdriver.Chrome()

# driver.get("https://www.selenium.dev/selenium/web/web-form.html")

# title = driver.title

# driver.implicitly_wait(0.5)

# text_box = driver.find_element(by=By.NAME, value="my-text")
# submit_button = driver.find_element(by=By.CSS_SELECTOR, value="button")

# text_box.send_keys("Selenium")
# submit_button.click()

# message = driver.find_element(by=By.ID, value="message")
# text = message.text

# driver.quit()

##################
# Generated by Selenium IDE
# import pytest
# import time
# import json
from selenium import webdriver
from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestClickingButtons():
#   def setup_method(self, method):
  def __init__(self):
    self.driver = webdriver.Firefox()
    # self.vars = {}

#   def test_basic_options():
#     options = webdriver.FirefoxOptions()
#     driver = webdriver.Firefox(options=options)

  def teardown_method(self, method):
    self.driver.quit()

#   def nav_back(self):
#     self.driver.back()
  
#   def test_clickingButtons(self):
#     self.driver.get("https://www.selenium.dev/selenium/web/click_tests/html5_submit_buttons.html")
#     self.driver.set_window_size(550, 692)
#     self.driver.find_element(By.ID, "name").click()
#     self.driver.find_element(By.ID, "name").send_keys("Shawn")
#     self.driver.find_element(By.ID, "internal_explicit_submit").click()
#     self.driver.find_element(By.ID, "internal_implicit_submit").click()
#     self.driver.find_element(By.ID, "internal_span_submit").click()
#     self.driver.find_element(By.ID, "external_explicit_submit").click()
#     self.driver.find_element(By.ID, "external_implicit_submit").click()

d = TestClickingButtons()
# d.test_basic_options()
# d.test_basic_options()
# d.test_clickingButtons()
d.driver.get("https://www.selenium.dev/selenium/web/click_tests/html5_submit_buttons.html")
d.driver.set_window_size(550, 692)
d.driver.find_element(By.ID, "name").click()
d.driver.find_element(By.ID, "name").send_keys("Shawn")# Find the label element 
label = d.driver.find_element(By.ID, "internal_explicit_submit").text
print("internal_explicit_submit label is: ",label)
lineHeight = d.driver.find_element(By.ID, "internal_explicit_submit").value_of_css_property("line-height")
print("internal_explicit_submit line height is: ",lineHeight)
size = d.driver.find_element(By.ID, "internal_explicit_submit").value_of_css_property("font-size")
print("internal_explicit_submit size is: ",size)
d.driver.find_element(By.ID, "internal_explicit_submit").click()
d.driver.back()
label = d.driver.find_element(By.ID, "internal_implicit_submit").text
print("internal_implicit_submit label is: ",label)
d.driver.find_element(By.ID, "internal_implicit_submit").click()
d.driver.back()
label = d.driver.find_element(By.ID, "internal_span_submit").text
print("internal_span_submit label is: ",label)
d.driver.find_element(By.ID, "internal_span_submit").click()
d.driver.back()
label = d.driver.find_element(By.ID, "external_explicit_submit").text
print("external_explicit_submit label is: ",label)
d.driver.find_element(By.ID, "external_explicit_submit").click()
d.driver.back()
label = d.driver.find_element(By.ID, "external_implicit_submit").text
print("external_implicit_submit label is: ",label)
d.driver.find_element(By.ID, "external_implicit_submit").click()
d.driver.back()
d.driver.quit()